// GAME STATUS
export const INTERACTING = 'INTERACTING'
export const VIEWING = 'VIEWING'
export const WON = 'WON'
export const LOST = 'LOST'


// TILE STATUS
export const FILLED_CORRECTLY = 'FILLED_CORRECTLY'
export const FILLED_INCORRECTLY = 'FILLED_INCORRECTLY'
export const UNFILLED_CORRECTLY = 'UNFILLED_CORRECTLY'
export const UNFILLED_INCORRECTLY = 'UNFILLED_INCORRECTLY'


// GAME BALANCE
export const PUNCH_FACTOR = 0.3